// @flow

import WithPost from '../../components/WithPost';

export default WithPost({
  "attributes": {
    "id": "2de31894-6830-48d7-a34f-9eaa72abc44b",
    "timestamp": 1382391734000,
    "title": "LaTeX šablona",
    "slug": "latex-sablona"
  },
  "body": "<p>Všiml si také někdo, že většina uživatelů WYSIWYG textového editoru typu Word v něm menšinu času píší a většinu času se snaží ohnout editor tak, aby dělal to co má? Tak přesně toto mě přestalo bavit a začal jsem všechny práce sázet v LaTeXu. Pro psaní mám vytvořenou následující šablonu, kterou s výhodou používám a zatím jsou na ní od kontrolujících dobré ohlasy (pokud si toho někdo všiml).</p>\n<pre><code class=\"lang-tex\">\\documentclass[12pt]{article} % use larger type; default would be 10pt\n\\usepackage[czech]{babel}\n\\usepackage[utf8]{inputenc} % set input encoding (not needed with XeLaTeX)\n\n%%% PAGE DIMENSIONS\n\\usepackage{geometry} % to change the page dimensions\n% \\usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}\n\\geometry{a4paper}\n\n\\usepackage{graphicx} % support the \\includegraphics command and options\n\\usepackage{wrapfig} % support the wrapfigure section\n\n\\usepackage{hyperref} % links in \\tableofcontents\n\\hypersetup{\n    colorlinks,\n    citecolor=black,\n    filecolor=black,\n    linkcolor=black,\n    urlcolor=black\n}\n\n% \\usepackage[parfill]{parskip} % Activate to begin paragraphs with an empty line rather than an indent\n\n%%% PACKAGES\n\\usepackage{booktabs} % for much better looking tables\n\\usepackage{array} % for better arrays (eg matrices) in maths\n%\\usepackage{paralist} % very flexible &amp; customisable lists (eg. enumerate/itemize, etc.)\n\\usepackage{verbatim} % adds environment for commenting out blocks of text &amp; for better verbatim\n\\usepackage{subfig} % make it possible to include more than one captioned figure/table in a single float\n% These packages are all incorporated in the memoir class to one degree or another...\n\\usepackage{tikz} % graphs\n\\usepackage{pgfplots}\n\\usepackage{float}\n\n%%% HEADERS &amp; FOOTERS\n\\usepackage{fancyhdr} % This should be set AFTER setting up the page geometry\n\\pagestyle{fancy} % options: empty , plain , fancy\n\\renewcommand{\\headrulewidth}{0pt} % customise the layout...\n\\lhead{}\\chead{}\\rhead{}\n\\lfoot{}\\cfoot{\\thepage}\\rfoot{}\n\n%%% SECTION TITLE APPEARANCE\n\\usepackage{sectsty}\n\\allsectionsfont{\\sffamily\\mdseries\\upshape} % (See the fntguide.pdf for font help)\n% (This matches ConTeXt defaults)\n\n%%% ToC (table of contents) APPEARANCE\n\\usepackage[nottoc,notlof,notlot]{tocbibind} % Put the bibliography in the ToC\n\\usepackage[titles,subfigure]{tocloft} % Alter the style of the Table of Contents\n\\renewcommand{\\cftsecfont}{\\rmfamily\\mdseries\\upshape}\n\\renewcommand{\\cftsecpagefont}{\\rmfamily\\mdseries\\upshape} % No bold!\n\newcommand{\\bigsize}{\\fontsize{35pt}{20pt}\\selectfont}\n\n%%% END Article customizations\n\n\\begin{document}\n\n    ...\n\n\\end{document}\n</code></pre>\n<p>Jsem relativně LaTeX nováčkem, proto by mě zajímalo. Používáte nějakou jinou šablonu? Lepší?</p>\n"
});
